WebApplication3/Controllers/KasutajaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication3;
using PagedList;

namespace WebApplication3 // Tegime partial classi et saaks oskust lisada
{
    partial class Kasutaja
    {
        public string LisaOskus { get; set; }
        public string LisaTase { get; set; }

    }
}

namespace WebApplication3.Controllers
{
    public class KasutajaController : Controller
    {
        private InimesedPadevusedEntities db = new InimesedPadevusedEntities();
        // GET: Kasutaja
        public ActionResult Index()
        {
            var kasutaja = db.Kasutaja.Include(k => k.Osakond);
            return View(kasutaja.ToList());
        }

        public ActionResult Nimekiri(string sortOrder, string searchWord, string currentFilter, int? page)
        {
            var kasutaja = from k in db.Kasutaja select k;

            var pageNumber = page ?? 1;
            int pageSize = 10;

            ViewBag.CurrentSort = sortOrder;

            if (searchWord != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchWord = currentFilter;
            }

            ViewBag.CurrentFilter = searchWord;

            if (!string.IsNullOrEmpty(searchWord))
            {
                kasutaja = kasutaja.Where(s => s.Nimi.Contains(searchWord.Trim()) 
                                            || s.Email.Contains(searchWord.Trim()) 
                                            || s.Osakond.Nimetus.Contains(searchWord.Trim())
                                            || s.KasutajaRoll.Select(k => k.Roll.Nimetus).Contains(searchWord.Trim())
                                            || s.KasutajaOskus.Select(k => k.Oskus.Nimetus).Contains(searchWord.Trim())
                                            || s.KasutajaOskus.Select(k => k.Tase.ToString()).Contains(searchWord.ToString())
                                            );
            }

            switch (sortOrder)
            {
                case "name_desc":
                    ViewBag.Suund = "name_desc";
                    kasutaja = kasutaja.OrderByDescending(x => x.Nimi).ThenBy(s => s.Id);
                    break;

                case "name_asc":
                    ViewBag.Suund = "name_asc";
                    kasutaja = kasutaja.OrderBy(x => x.Nimi).ThenBy(s => s.Id);
                    break;

                case "email_desc":
                    ViewBag.Email = "email_desc";
                    kasutaja = kasutaja.OrderBy(x => x.Email);
                    break;

                case "email_asc":
                    ViewBag.Email = "email_asc";
                    kasutaja = kasutaja.OrderByDescending(x => x.Email);
                    break;

                case "osak_desc":
                    ViewBag.Osak = "osak_desc";
                    kasutaja = kasutaja.OrderBy(x => x.Osakond.Nimetus);
                    break;

                case "osak_asc":
                    ViewBag.Osak = "osak_asc";
                    kasutaja = kasutaja.OrderByDescending(x => x.Osakond.Nimetus);
                    break;

                case "oskus_desc":
                    ViewBag.Oskus = "oskus_desc";
                    kasutaja = kasutaja.OrderBy(x => x.KasutajaOskus.Select(y => y.Oskus.Nimetus).SingleOrDefault());
                    break;

                case "oskus_asc":
                    ViewBag.Oskus = "oskus_asc";
                    kasutaja = kasutaja.OrderByDescending(x => x.KasutajaOskus.Select(y => y.Oskus.Nimetus).SingleOrDefault());
                    break;

                case "inaktiv":
                    ViewBag.Akt = "inaktiv";
                    kasutaja = kasutaja.OrderBy(x => x.Aktiivsus);
                    break;

                case "aktiv":
                    ViewBag.Akt = "aktiv";
                    kasutaja = kasutaja.OrderByDescending(x => x.Aktiivsus);
                    break;
                    
                default:
                    kasutaja = kasutaja.OrderBy(x => x.Nimi);
                    break;
            }

            var onePageOfNames = kasutaja.ToPagedList(pageNumber, pageSize);
            ViewBag.OnePageOfNames= onePageOfNames;

            return View(kasutaja.ToPagedList(pageNumber, pageSize));
            
        }

        // GET: Kasutaja/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Kasutaja kasutaja = db.Kasutaja.Find(id);
            if (kasutaja == null)
            {
                return HttpNotFound();
            }
            ViewBag.Kasutaja = kasutaja.Email;

            return View(kasutaja);
        }

        // GET: Kasutaja/Create
        public ActionResult Create()
        {
            ViewBag.OsakondID = new SelectList(db.Osakond, "Id", "Nimetus");
            return View();
        }

        // POST: Kasutaja/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Email,Nimi,OsakondID, Aktiivsus")] Kasutaja kasutaja)
        {
            if (ModelState.IsValid)
            {
                db.Kasutaja.Add(kasutaja);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.OsakondID = new SelectList(db.Osakond, "Id", "Nimetus", kasutaja.OsakondID);
            return View(kasutaja);
        }

        // GET: Kasutaja/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Kasutaja kasutaja = db.Kasutaja.Find(id);
            if (kasutaja == null)
            {
                return HttpNotFound();
            }
            ViewBag.Kasutaja = kasutaja.Email;
            ViewBag.OsakondID = new SelectList(db.Osakond, "Id", "Nimetus", kasutaja.OsakondID);

            kasutaja.LisaOskus = "";
            kasutaja.LisaTase = "";
            return View(kasutaja);
        }

        // POST: Kasutaja/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        //TODO SIIN PEAB UURIMA KUIDAS KORDA TEHA!!!
        //[ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Email,Nimi,OsakondID, Aktiivsus, LisaOskus")] Kasutaja kasutaja)
        {
            if (ModelState.IsValid)
            {
                db.Entry(kasutaja).State = EntityState.Modified;
                db.SaveChanges();
                //return RedirectToAction("Index");
                string lisaOskus = (kasutaja.LisaOskus + "").Trim().ToLower();
                if (lisaOskus == "") return RedirectToAction("Index");
                Oskus oskused = db.Oskus.Where(x => x.Nimetus.ToLower() == lisaOskus).Take(1).SingleOrDefault();
                if (oskused == null)
                {
                    oskused = new Oskus { Nimetus = kasutaja.LisaOskus };
                    db.SaveChanges();
                }
                kasutaja.KasutajaOskus.Add(new KasutajaOskus { Oskus = oskused });
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Kasutaja = kasutaja.Email;
            ViewBag.OsakondID = new SelectList(db.Osakond, "Id", "Nimetus", kasutaja.OsakondID);
            return View(kasutaja);
        }

        // GET: Kasutaja/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Kasutaja kasutaja = db.Kasutaja.Find(id);
            if (kasutaja == null)
            {
                return HttpNotFound();
            }
            return View(kasutaja);
        }

        // POST: Kasutaja/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Kasutaja kasutaja = db.Kasutaja.Find(id);
            db.Kasutaja.Remove(kasutaja);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplication3/Controllers/KasutajaOskusController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication3;
using PagedList;
using System.Data.Entity.Core.Objects;

namespace WebApplication3.Controllers
{
    
    public class KasutajaOskusController : Controller
    {
        private InimesedPadevusedEntities db = new InimesedPadevusedEntities();

        // GET: KasutajaOskus
        public ActionResult Index(string sortOrder, string currentFilter, string searchWord, int? page)
        {
            //var kasutajaOskus = kasutajaOskusAlg.ToList();

            var pageNumber = page ?? 1;
            int pageSize = 10;

            var kasutajaOskus = from k in db.KasutajaOskus select k;

            ViewBag.CurrentSort = sortOrder;

            if (searchWord != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchWord = currentFilter;
            }

            ViewBag.CurrentFilter = searchWord;

            if (!string.IsNullOrEmpty(searchWord))
            {
                kasutajaOskus = kasutajaOskus.Where(s => s.Kasutaja.Nimi.Contains(searchWord.Trim())
                                                        || s.Oskus.Nimetus.Contains(searchWord.Trim())
                                                        || s.Tase.ToString().Contains(searchWord.ToString().Trim())
                                                        );
            }

            switch (sortOrder)
            {
                case "date_desc":
                    ViewBag.Date = "date_desc";
                    kasutajaOskus = kasutajaOskus.OrderByDescending(x => x.Kuupäev);
                    break;

                case "date_asc":
                    ViewBag.Date = "date_asc";
                    kasutajaOskus = kasutajaOskus.OrderBy(x => x.Kuupäev);
                    break;

                case "name_desc":
                    ViewBag.Name = "name_desc";
                    kasutajaOskus = kasutajaOskus.OrderByDescending(x => x.Kasutaja.Nimi).ThenBy(s => s.KasutajaId);
                    break;

                case "name_asc":
                    ViewBag.Name = "name_asc";
                    kasutajaOskus = kasutajaOskus.OrderBy(x => x.Kasutaja.Nimi).ThenBy(s => s.KasutajaId);
                    break;

                case "oskus_desc":
                    ViewBag.Name = "oskus_desc";
                    kasutajaOskus = kasutajaOskus.OrderByDescending(x => x.Oskus.Nimetus).ThenBy(s => s.Tase);
                    break;

                case "oskus_asc":
                    ViewBag.Name = "oskus_asc";
                    kasutajaOskus = kasutajaOskus.OrderBy(x => x.Oskus.Nimetus).ThenBy(s => s.Tase);
                    break;

                case "tase_desc":
                    ViewBag.Name = "tase_desc";
                    kasutajaOskus = kasutajaOskus.OrderByDescending(x => x.Tase);
                    break;

                case "tase_asc":
                    ViewBag.Name = "tase_asc";
                    kasutajaOskus = kasutajaOskus.OrderBy(x => x.Tase);
                    break;

                default:
                    ViewBag.Name = "name_asc";
                    kasutajaOskus = kasutajaOskus.OrderBy(x => x.Kasutaja.Nimi);
                    break;
            }

            var onePageOfSkills = kasutajaOskus.ToPagedList(pageNumber, pageSize);
            ViewBag.OnePageOfSkills = onePageOfSkills;

            return View(kasutajaOskus.ToPagedList(pageNumber, pageSize));
        }

        [HttpPost]
        public ActionResult Upload (HttpPostedFileBase postedFile,int? id)
        {
            KasutajaOskus kasutajaOskus = db.KasutajaOskus.Find(id);
            if (postedFile == null)
            {
                ViewBag.Message = "Please sellect file!";
                return View();
            }
            else if (postedFile != null)
            {
                string path = Server.MapPath("~/Uploads/");
 
                if (!Directory.Exists(path))
                {
                    Directory.CreateDirectory(path);
                }

                postedFile.SaveAs(path + Path.GetFileName(postedFile.FileName));
                ViewBag.Message9 = "File uploaded successfully!";

            }
            return View();
        }

        // GET: KasutajaOskus/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            KasutajaOskus kasutajaOskus = db.KasutajaOskus.Find(id);
            if (kasutajaOskus == null)
            {
                return HttpNotFound();
            }
            ViewBag.Kasutaja = kasutajaOskus.Kasutaja.Email;

            return View(kasutajaOskus);
        }
        
        // GET: KasutajaOskus/Create
        public ActionResult Create()
        {
            ViewBag.KasutajaId = new SelectList(db.Kasutaja, "Id", "Email");
            ViewBag.OskusId = new SelectList(db.Oskus, "Id", "Nimetus");
            return View();
        }

        // POST: KasutajaOskus/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,KasutajaId,OskusId,Tase,Kuupäev")] KasutajaOskus kasutajaOskus)
        {
            if (ModelState.IsValid)
            {
                db.KasutajaOskus.Add(kasutajaOskus);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.KasutajaId = new SelectList(db.Kasutaja, "Id", "Email", kasutajaOskus.KasutajaId);
            ViewBag.OskusId = new SelectList(db.Oskus, "Id", "Nimetus", kasutajaOskus.OskusId);
            return View(kasutajaOskus);
        }

        // GET: KasutajaOskus/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            KasutajaOskus kasutajaOskus = db.KasutajaOskus.Find(id);
            if (kasutajaOskus == null)
            {
                return HttpNotFound();
            }

            ViewBag.Kasutaja = db.KasutajaOskus.Find(id).Kasutaja.Email;
                
            ViewBag.KasutajaId = new SelectList(db.Kasutaja, "Id", "Email", kasutajaOskus.KasutajaId);
            ViewBag.OskusId = new SelectList(db.Oskus, "Id", "Nimetus", kasutajaOskus.OskusId);

            return View(kasutajaOskus);
           
        }

        // POST: KasutajaOskus/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,KasutajaId,OskusId,Tase,Kuupäev,LisaOskus")] KasutajaOskus kasutajaOskus)
        {
            if (ModelState.IsValid)
            {
                db.Entry(kasutajaOskus).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Kasutaja = kasutajaOskus.Kasutaja.Email;

            ViewBag.KasutajaId = new SelectList(db.Kasutaja, "Id", "Email", kasutajaOskus.KasutajaId);
            ViewBag.OskusId = new SelectList(db.Oskus, "Id", "Nimetus", kasutajaOskus.OskusId);
            return View(kasutajaOskus);
        }

        // GET: KasutajaOskus/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            KasutajaOskus kasutajaOskus = db.KasutajaOskus.Find(id);
            if (kasutajaOskus == null)
            {
                return HttpNotFound();
            }
            ViewBag.Kasutaja = kasutajaOskus.Kasutaja.Email;

            return View(kasutajaOskus);
        }

        // POST: KasutajaOskus/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            KasutajaOskus kasutajaOskus = db.KasutajaOskus.Find(id);
            db.KasutajaOskus.Remove(kasutajaOskus);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplication3/Views/KasutajaOskus/Create.cshtml
@model WebApplication3.KasutajaOskus

@{
    ViewBag.Title = "Create";
}

@{
    if (User.Identity.IsAuthenticated && Kasutaja.ByEmail(User.Identity.Name) != null && Roll.KasOnAdmin(Roll.ByRollId(KasutajaRoll.ById(Kasutaja.ByEmail(User.Identity.Name).Id).RollId).Id) == true)
    {
        <h2>Lisa kasutajale uus oskus</h2>


        using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h4>Kasutaja oskus</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.KasutajaId, "KasutajaId", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("KasutajaId", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.KasutajaId, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.OskusId, "OskusId", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("OskusId", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.OskusId, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Tase, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Tase, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Tase, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Kuupäev, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextBox("Kuupäev", DateTime.Now.ToShortDateString(), new { @readonly = true, @class = "form-control" } )
                        @*@Html.EditorFor(model => model.Kuupäev, new { htmlAttributes = new { @class = "form-control" } })*@
                        @Html.ValidationMessageFor(model => model.Kuupäev, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Create" class="btn btn-default" />
                    </div>
                </div>
            </div>
        }

        <div>
            @Html.ActionLink("Tagasi kasutajate oskuste nimekirja", "Index")
        </div>
    }
    else
    {
        Write("Siin pole mitte midagi. Mine ära. >:(");
    }
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebApplication3/Views/KasutajaOskus/Index.cshtml
@model IEnumerable<WebApplication3.KasutajaOskus>

@using PagedList.Mvc;
@using PagedList;

@{
    ViewBag.Title = "Index";
}

@{
    if (!User.Identity.IsAuthenticated && Kasutaja.ByEmail(User.Identity.Name) == null)
    {

        <p>Siin pole mitte midagi. Mine ära. >:(</p>
    }
    else
    {
        KasutajaRoll k = KasutajaRoll.ById(Kasutaja.ByEmail(User.Identity.Name).Id) ?? null;
        if (k == null)
        {
            <p>
                Nägemiseks on vajalik roll - Teil puudub see. Paluge adminnil endale roll määrata.
            </p>
        }
        else
        {
            <h2>Kasutajate oskuste nimekiri</h2>

            <p>
                @Html.ActionLink("Lisa endale uus oskus", "Edit", "Kasutaja", new { id = Kasutaja.ByEmail(User.Identity.Name).Id }, null)
                <br />
                @Html.ActionLink("Andmebaasis olevate oskuste nimekiri", "Index", "Oskus")
                <br />
                @Html.ActionLink("Lisa uus oskus nimekirja", "Create", "Oskus")
                @if (Roll.KasOnAdmin(Roll.ByRollId(KasutajaRoll.ById(Kasutaja.ByEmail(User.Identity.Name).Id).RollId).Id) == true)
                {
                    <br />
                    @Html.ActionLink("Lisa kasutajale uus oskus", "Create")
                }
            </p>

            using (Html.BeginForm("Index", "KasutajaOskus", FormMethod.Get))
            {
                <p>
                    Otsi termini järgi: @Html.TextBox("searchWord", ViewBag.CurrentFilter as string)
                    <input type="submit" value="Otsi" class="btn btn-default" />
                    <input type="button" onclick="location.href = '@Url.Action("Index", "KasutajaOskus", new { searchWord = "" })'" value="Reset" class="btn btn-default" />
                </p>
            }

            <table class="table">
                <tr>
                    @if (Roll.KasOnAdmin(Roll.ByRollId(KasutajaRoll.ById(Kasutaja.ByEmail(User.Identity.Name).Id).RollId).Id) == true)
                    {
                        <th>
                            @Html.DisplayNameFor(model => model.Kuupäev)

                            @if (ViewBag.Date == "date_asc")
                            {
                                <a href="@Url.Action("Index", "KasutajaOskus", new { sortOrder = "date_desc", currentFilter = ViewBag.CurrentFilter })">
                                    <img class="arrow-inverted" src="\Projekt items\aiga-down-arrow-bg-800px.png" alt="arrow" width="15" />
                                </a>
                            }
                            else
                            {
                                <a href="@Url.Action("Index", "KasutajaOskus", new { sortOrder = "date_asc", currentFilter = ViewBag.CurrentFilter })">
                                    <img class="arrow-regular" src="\Projekt items\aiga-down-arrow-bg-800px.png" alt="arrow" width="15" />
                                </a>
                            }
                        </th>
                    }
                    <th>
                        @Html.DisplayNameFor(model => model.Kasutaja.Nimi)

                        @if (ViewBag.name == "name_asc")
                        {
                            <a href="@Url.Action("Index", "KasutajaOskus", new { sortOrder = "name_desc", currentFilter = ViewBag.CurrentFilter })">
                                <img class="arrow-inverted" src="\Projekt items\aiga-down-arrow-bg-800px.png" alt="arrow" width="15" />
                            </a>
                        }
                        else
                        {
                            <a href="@Url.Action("Index", "KasutajaOskus", new { sortOrder = "name_asc", currentFilter = ViewBag.CurrentFilter })">
                                <img class="arrow-regular" src="\Projekt items\aiga-down-arrow-bg-800px.png" alt="arrow" width="15" />
                            </a>
                        }
                    </th>
                    <th>
                        Oskus

                        @if (ViewBag.name == "oskus_asc")
                        {
                            <a href="@Url.Action("Index", "KasutajaOskus", new { sortOrder = "oskus_desc", currentFilter = ViewBag.CurrentFilter })">
                                <img class="arrow-inverted" src="\Projekt items\aiga-down-arrow-bg-800px.png" alt="arrow" width="15" />
                            </a>
                        }
                        else
                        {
                            <a href="@Url.Action("Index", "KasutajaOskus", new { sortOrder = "oskus_asc", currentFilter = ViewBag.CurrentFilter })">
                                <img class="arrow-regular" src="\Projekt items\aiga-down-arrow-bg-800px.png" alt="arrow" width="15" />
                            </a>
                        }
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Tase)

                        @if (ViewBag.name == "tase_asc")
                        {
                            <a href="@Url.Action("Index", "KasutajaOskus", new { sortOrder = "tase_desc", currentFilter = ViewBag.CurrentFilter })">
                                <img class="arrow-inverted" src="\Projekt items\aiga-down-arrow-bg-800px.png" alt="arrow" width="15" />
                            </a>
                        }
                        else
                        {
                            <a href="@Url.Action("Index", "KasutajaOskus", new { sortOrder = "tase_asc", currentFilter = ViewBag.CurrentFilter })">
                                <img class="arrow-regular" src="\Projekt items\aiga-down-arrow-bg-800px.png" alt="arrow" width="15" />
                            </a>
                        }
                    </th>
                    <th></th>
                </tr>

                @foreach (var item in Model)
                {
                    <tr>
                        @if (Roll.KasOnAdmin(Roll.ByRollId(KasutajaRoll.ById(Kasutaja.ByEmail(User.Identity.Name).Id).RollId).Id) == true)
                        {
                            <td>
                                @if (item.Kuupäev.HasValue)
                                {
                                    DateTime? dt = (DateTime?)item.Kuupäev;
                                    string dateT = string.Format("{0:d}", dt);
                                    @Html.DisplayFor(modelItem => dateT);
                                }
                                @*@Html.DisplayFor(modelItem => item.Kuupäev.Value.ToShortDateString()) <-- seda ei saa teha, sest displayfor ei salli meetodit!*@
                            </td>
                        }
                        <td>
                            @if (Roll.KasOnEmployee(Roll.ByRollId(KasutajaRoll.ById(Kasutaja.ByEmail(User.Identity.Name).Id).RollId).Id) == true
                                && Roll.KasOnAdmin(Roll.ByRollId(KasutajaRoll.ById(Kasutaja.ByEmail(User.Identity.Name).Id).RollId).Id) == false
                                && item.Kasutaja.Id != Kasutaja.ByEmail(User.Identity.Name).Id)
                            {
                                @Html.DisplayFor(modelItem => item.Kasutaja.Nimi)
                            }
                            else
                            {
                                <b class="custom-link">
                                    @Html.ActionLink(item.Kasutaja.Nimi, "Details", "Kasutaja", new { id = item.Kasutaja.Id }, null)
                                </b>
                            }
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Oskus.Nimetus)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Tase)
                        </td>
                        <td>
                            @if (item.Kasutaja.Id == Kasutaja.ByEmail(User.Identity.Name).Id && Roll.KasOnAdmin(Roll.ByRollId(KasutajaRoll.ById(Kasutaja.ByEmail(User.Identity.Name).Id).RollId).Id) == false)
                            {
                                @Html.ActionLink("Muuda", "Edit", new { id = item.Id })
                            }

                            @if (Roll.KasOnAdmin(Roll.ByRollId(KasutajaRoll.ById(Kasutaja.ByEmail(User.Identity.Name).Id).RollId).Id) == true)
                            {
                                <text>
                                    @Html.ActionLink("Muuda", "Edit", new { id = item.Id })  |
                                    @Html.ActionLink("Detailid", "Details", new { id = item.Id }) |
                                    @Html.ActionLink("Kustuta", "Delete", new { id = item.Id })
                                </text>
                            }
                        </td>
                    </tr>
                }

            </table>
            <br />
            
            @Html.PagedListPager((IPagedList)ViewBag.OnePageOfSkills, page => Url.Action("Index", new { sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter, page }), PagedListRenderOptions.OnlyShowFivePagesAtATime)
        }
    }

}

WebApplication3/Views/KasutajaOskus/Upload.cshtml
@model IEnumerable<WebApplication3.KasutajaOskus>

@{
    ViewBag.Title = "Upload";
}