WebApplication3/Controllers/KasutajaRollsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication3;

namespace WebApplication3
{
    partial class Kasutaja
    {
        // selle rea võiks iga dataklassi laienduse ja kontrolleri algusse lisada
        static InimesedPadevusedEntities db = new InimesedPadevusedEntities();

        // Tänu sellele funktsioonile saame emaili järgi kasutaja
        public static Kasutaja ByEmail(string email)
        {
            return db.Kasutaja.Where(x => x.Email == email).Take(1).SingleOrDefault();  //Kui meie kasutaja andmebaasis ei leita vastava emailiga tegelast, siis annab väärtuse null
        }

        public static Kasutaja ById(int? id)
        {
            return db.Kasutaja.Where(x => x.Id == id).Take(1).SingleOrDefault();
        }
    }
    partial class KasutajaRoll
    {
        // selle rea võiks iga dataklassi laienduse ja kontrolleri algusse lisada
        static InimesedPadevusedEntities db = new InimesedPadevusedEntities();

        // Tänu sellele funktsioonile saame Kasutaja tabeli Id järgi RollId KasutajaRoll tabelist
        public static KasutajaRoll ById(int id)
        {
            return db.KasutajaRoll.Where(x => x.KasutajaId == id).Take(1).SingleOrDefault();  //
        }
    }
    partial class Roll
    {
        // selle rea võiks iga dataklassi laienduse ja kontrolleri algusse lisada
        static InimesedPadevusedEntities db = new InimesedPadevusedEntities();

        // Tänu sellele funktisoonile saame KasutajaRoll tabeli RollId järgi Roll tabelist Id
        public static Roll ByRollId(int rollId)
        {
            return db.Roll.Where(x => x.Id == rollId).Take(1).SingleOrDefault();  //
        }
        
        //Meetod kontrollimaks, kas tegu on adminiga
        static bool OnAdmin = false;
        public static bool KasOnAdmin(int rollId)
        {
            if(rollId == 2)
            {return OnAdmin = true;}
            else
            {return OnAdmin = false;}
        }
        
        //Meetod kontrollimaks, kas tegu on employeega
        static bool OnEmployee = false;
        public static bool KasOnEmployee(int rollId)
        {
            if (rollId == 1)
            { return OnEmployee = true; }
            else
            { return OnEmployee = false; }
        }

        //Meetod kontrollimaks, kas tegu on manageriga
        static bool OnManager = false;
        public static bool KasOnManager(int rollId)
        {
            if (rollId == 3)
            { return OnManager = true; }
            else
            { return OnManager = false; }
        }

    }
   
}
namespace WebApplication3.Controllers
{

    public class KasutajaRollsController : Controller
    {
        private InimesedPadevusedEntities db = new InimesedPadevusedEntities();

        // GET: KasutajaRolls
        public ActionResult Index(string sortOrder)
        {
            var kasutajaRoll = db.KasutajaRoll.Include(k => k.Kasutaja).Include(k => k.Roll);
            
            switch (sortOrder)
            {
                case "nimi_desc":
                    ViewBag.Nimi = "nimi_desc";
                    return View(kasutajaRoll.ToList().OrderByDescending(x => x.Kasutaja.Nimi).ThenBy(s => s.Kasutaja.Id));
                        
                case "nimi_asc":
                    ViewBag.Nimi = "nimi_asc";
                    return View(kasutajaRoll.ToList().OrderBy(x => x.Kasutaja.Nimi).ThenBy(s => s.Kasutaja.Id));

                case "email_desc":
                    ViewBag.Email = "email_desc";
                    return View(kasutajaRoll.ToList().OrderByDescending(x => x.Kasutaja.Email));

                case "email_asc":
                    ViewBag.Email = "email_asc";
                    return View(kasutajaRoll.ToList().OrderBy(x => x.Kasutaja.Email));

                case "roll_desc":
                    ViewBag.Roll = "roll_desc";
                    return View(kasutajaRoll.ToList().OrderByDescending(x => x.Roll.Nimetus));

                case "roll_asc":
                    ViewBag.Roll = "roll_asc";
                    return View(kasutajaRoll.ToList().OrderBy(x => x.Roll.Nimetus));

                default:
                    ViewBag.Nimi = "nimi_asc";
                    return View(kasutajaRoll.ToList().OrderBy(x => x.Kasutaja.Nimi).ThenBy(s => s.Kasutaja.Id));
            }
        }

        // GET: KasutajaRolls/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            KasutajaRoll kasutajaRoll = db.KasutajaRoll.Find(id);
            if (kasutajaRoll == null)
            {
                return HttpNotFound();
            }
            return View(kasutajaRoll);
        }

        // GET: KasutajaRolls/Create
        public ActionResult Create()
        {
            ViewBag.KasutajaId = new SelectList(db.Kasutaja, "Id", "Email");
            ViewBag.RollId = new SelectList(db.Roll, "Id", "Nimetus");
            return View();
        }

        // POST: KasutajaRolls/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,KasutajaId,RollId")] KasutajaRoll kasutajaRoll)
        {
            if (ModelState.IsValid)
            {
                db.KasutajaRoll.Add(kasutajaRoll);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.KasutajaId = new SelectList(db.Kasutaja, "Id", "Email", kasutajaRoll.KasutajaId);
            ViewBag.RollId = new SelectList(db.Roll, "Id", "Nimetus", kasutajaRoll.RollId);
            return View(kasutajaRoll);
        }

        // GET: KasutajaRolls/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            KasutajaRoll kasutajaRoll = db.KasutajaRoll.Find(id);
            if (kasutajaRoll == null)
            {
                return HttpNotFound();
            }
            ViewBag.KasutajaId = new SelectList(db.Kasutaja, "Id", "Email", kasutajaRoll.KasutajaId);
            ViewBag.RollId = new SelectList(db.Roll, "Id", "Nimetus", kasutajaRoll.RollId);
            return View(kasutajaRoll);
        }

        // POST: KasutajaRolls/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,KasutajaId,RollId")] KasutajaRoll kasutajaRoll)
        {
            if (ModelState.IsValid)
            {
                db.Entry(kasutajaRoll).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.KasutajaId = new SelectList(db.Kasutaja, "Id", "Email", kasutajaRoll.KasutajaId);
            ViewBag.RollId = new SelectList(db.Roll, "Id", "Nimetus", kasutajaRoll.RollId);
            return View(kasutajaRoll);
        }

        // GET: KasutajaRolls/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            KasutajaRoll kasutajaRoll = db.KasutajaRoll.Find(id);
            if (kasutajaRoll == null)
            {
                return HttpNotFound();
            }
            return View(kasutajaRoll);
        }

        // POST: KasutajaRolls/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            KasutajaRoll kasutajaRoll = db.KasutajaRoll.Find(id);
            db.KasutajaRoll.Remove(kasutajaRoll);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplication3/Controllers/RollsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication3;

namespace WebApplication3.Controllers
{
    public class RollsController : Controller
    {
        private InimesedPadevusedEntities db = new InimesedPadevusedEntities();

        // GET: Rolls
        public ActionResult Index()
        {
            return View(db.Roll.ToList());
        }

        // GET: Rolls/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Roll roll = db.Roll.Find(id);
            if (roll == null)
            {
                return HttpNotFound();
            }
            return View(roll);
        }

        // GET: Rolls/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Rolls/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Nimetus")] Roll roll)
        {
            if (ModelState.IsValid)
            {
                db.Roll.Add(roll);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(roll);
        }

        // GET: Rolls/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Roll roll = db.Roll.Find(id);
            if (roll == null)
            {
                return HttpNotFound();
            }
            return View(roll);
        }

        // POST: Rolls/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Nimetus")] Roll roll)
        {
            if (ModelState.IsValid)
            {
                db.Entry(roll).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(roll);
        }

        // GET: Rolls/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Roll roll = db.Roll.Find(id);
            if (roll == null)
            {
                return HttpNotFound();
            }
            return View(roll);
        }

        // POST: Rolls/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Roll roll = db.Roll.Find(id);
            db.Roll.Remove(roll);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplication3/Views/KasutajaRolls/Create.cshtml
@model WebApplication3.KasutajaRoll

@{
    ViewBag.Title = "Anna";
}

@{
    if (User.Identity.IsAuthenticated && Kasutaja.ByEmail(User.Identity.Name) != null && Roll.KasOnAdmin(Roll.ByRollId(KasutajaRoll.ById(Kasutaja.ByEmail(User.Identity.Name).Id).RollId).Id) == true)
    {
        <h2>Anna kasutajale roll</h2>


        using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">

                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.KasutajaId, "Kasutaja", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("KasutajaId", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.KasutajaId, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.RollId, "Roll", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("RollId", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.RollId, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Loo" class="btn btn-default" />
                    </div>
                </div>
            </div>
        }

        <div>
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
    else
    {
        Write("Siin pole mitte midagi. Mine ära. >:(");
    }
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebApplication3/Views/KasutajaRolls/Delete.cshtml
@model WebApplication3.KasutajaRoll

@{
    ViewBag.Title = "Kustuta";
}

@{
    if (User.Identity.IsAuthenticated && Kasutaja.ByEmail(User.Identity.Name) != null && Roll.KasOnAdmin(Roll.ByRollId(KasutajaRoll.ById(Kasutaja.ByEmail(User.Identity.Name).Id).RollId).Id) == true)
    {
        <h2>Eemalda roll</h2>

        <h3>Oled sa kindel, et tahad selle kasutaja rolli eemaldada?</h3>
        <div>
            
            <hr />
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.Kasutaja.Email)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Kasutaja.Email)
                </dd>

                <dt>
                    Roll
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Roll.Nimetus)
                </dd>

            </dl>

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-actions no-color">
                    <input type="submit" value="Delete" class="btn btn-default" /> |
                    @Html.ActionLink("Tagasi nimekirja", "Index")
                </div>
            }
        </div>
    }
    else
    {
        Write("Siin pole mitte midagi. Mine ära. >:(");
    }
}

WebApplication3/Views/KasutajaRolls/Details.cshtml
@model WebApplication3.KasutajaRoll

@{
    ViewBag.Title = "Details";
}

@{
    if (true)
    {
        Write("Siin pole mitte midagi. Mine ära. >:(");
    }
    else
    {
        <h2>Detailid</h2>


        <div>
            <h4>KasutajaRoll</h4>
            <hr />
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.Kasutaja.Email)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Kasutaja.Email)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Roll.Nimetus)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Roll.Nimetus)
                </dd>

            </dl>
        </div>
        <p>
            @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
            @Html.ActionLink("Back to List", "Index")
        </p>
    }
}

WebApplication3/Views/KasutajaRolls/Edit.cshtml
@model WebApplication3.KasutajaRoll

@{
    ViewBag.Title = "Edit";
}

@{
    if (User.Identity.IsAuthenticated && Kasutaja.ByEmail(User.Identity.Name) != null && Roll.KasOnAdmin(Roll.ByRollId(KasutajaRoll.ById(Kasutaja.ByEmail(User.Identity.Name).Id).RollId).Id) == true)
    {
        <h2>Muuda Rolli</h2>


        using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h4>KasutajaRoll</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.Id)

                <div class="form-group">
                    @Html.LabelFor(model => model.KasutajaId, "KasutajaId", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("KasutajaId", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.KasutajaId, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.RollId, "RollId", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("RollId", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.RollId, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Save" class="btn btn-default" />
                    </div>
                </div>
            </div>
        }

        <div>
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
    else
    {
        Write("Siin pole mitte midagi. Mine ära. >:(");
    }
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebApplication3/Views/KasutajaRolls/Index.cshtml
@model IEnumerable<WebApplication3.KasutajaRoll>

@{
    ViewBag.Title = "Index";
}


@{
    <h2>Index</h2>

    if (User.Identity.IsAuthenticated && Kasutaja.ByEmail(User.Identity.Name) != null && Roll.KasOnAdmin(Roll.ByRollId(KasutajaRoll.ById(Kasutaja.ByEmail(User.Identity.Name).Id).RollId).Id) == true)
    {
        <p>
            @Html.ActionLink("Anna kasutajale roll", "Create")
            <br />
            @Html.ActionLink("Rollide nimekiri", "Index", "Rolls")
        </p>
    }


    if (User.Identity.IsAuthenticated && Kasutaja.ByEmail(User.Identity.Name) != null && Roll.KasOnAdmin(Roll.ByRollId(KasutajaRoll.ById(Kasutaja.ByEmail(User.Identity.Name).Id).RollId).Id) == true)
    {

        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Kasutaja.Nimi)


                    @if (ViewBag.Nimi == "nimi_asc")
                    {
                        <a href="@Url.Action("Index", "KasutajaRolls", new { sortOrder = "nimi_desc" })">
                            <img class="arrow-inverted" src="\Projekt items\aiga-down-arrow-bg-800px.png" alt="arrow" width="15" />
                        </a>
                    }
                    else
                    {
                        <a href="@Url.Action("Index", "KasutajaRolls", new { sortOrder = "nimi_asc" })">
                            <img class="arrow-regular" src="\Projekt items\aiga-down-arrow-bg-800px.png" alt="arrow" width="15" />
                        </a>
                    }
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Kasutaja.Email)

                    @if (ViewBag.Email == "email_asc")
                    {
                        <a href="@Url.Action("Index", "KasutajaRolls", new { sortOrder = "email_desc" })">
                            <img class="arrow-inverted" src="\Projekt items\aiga-down-arrow-bg-800px.png" alt="arrow" width="15" />
                        </a>
                    }
                    else
                    {
                        <a href="@Url.Action("Index", "KasutajaRolls", new { sortOrder = "email_asc" })">
                            <img class="arrow-regular" src="\Projekt items\aiga-down-arrow-bg-800px.png" alt="arrow" width="15" />
                        </a>
                    }
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Roll)


                    @if (ViewBag.Roll == "roll_asc")
                    {
                        <a href="@Url.Action("Index", "KasutajaRolls", new { sortOrder = "roll_desc" })">
                            <img class="arrow-inverted" src="\Projekt items\aiga-down-arrow-bg-800px.png" alt="arrow" width="15" />
                        </a>
                    }
                    else
                    {
                        <a href="@Url.Action("Index", "KasutajaRolls", new { sortOrder = "roll_asc" })">
                            <img class="arrow-regular" src="\Projekt items\aiga-down-arrow-bg-800px.png" alt="arrow" width="15" />
                        </a>
                    }
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Kasutaja.Nimi)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Kasutaja.Email)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Roll.Nimetus)
                    </td>
                    <td>
                        @Html.ActionLink("Muuda", "Edit", new { id = item.Id }) |
                        @Html.ActionLink("Detailid", "Details", new { id = item.Id }) |
                        @Html.ActionLink("Kustuta", "Delete", new { id = item.Id })


                    </td>
                </tr>
            }

        </table>
    }
    else
    {
        Write("Siin pole mitte midagi. Mine ära. >:(");
    }
}